### ISSUE TITLE
stepper motors support

### ISSUE THREAD

**Issue by darkworks** [jeroenwalter/Arduino#21]
hi thanks for amazing project , am working stepper motors , so can i control stepper motors with it ? if not how can we add stepper motor support to it

thanks

**Comment by jeroenwalter** [comment]
I think this library supports it.
The method SetDigitalPinMode can be used to put a pin in servo mode.
The method SetDigitalPin can be used to (de)activate a servo motor.
The method ConfigureServo can be used to configure the minimum and maximum pulse length for a servo pin.

But please ask your questions on the original github, https://github.com/SolidSoils/Arduino
I've just forked this repo to add .net core 3.0 support and I haven't had time to finish that. 
Also I don't use servos.
